INCLUDES=-I../../../include -I../../../bulb/include
CXX=clang++
CXXFLAGS=-std=c++11 -stdlib=libc++ -Wall -pedantic $(INCLUDES)
LDFLAGS=-lboost_system-mt

all: learning_switch

clean:
	-rm learning_switch

